name: Test run img rust-plus-container
on:
  workflow_call:
  workflow_dispatch:

jobs:
  test_access:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/digikata/rust-plus-container:latest

    steps:
      - name: test shell access
        run: |
          echo check cargo
          cargo version        
          echo check aws
          aws --version
          echo check helm
          helm version

      - uses: actions/checkout@v3
      - name: test repo access
        run: actions/test_access.sh
