name: Test run img
on:
  workflow_dispatch:

jobs:
  test_access:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/digikata/rust-plus-container:latest

    steps:
      - name: test access
        run: actions/test_access.sh
